// Bangla Keyboard — phonetic engine regression corpus (Banglish input -> NFC Bangla).
//
// The authoritative behaviour spec for transliterate() (PHONETIC.md §7). Curated
// rule-isolating cases + strict pairs from an adversarially spell-checked corpus (two
// independent native-level review passes; only pairs the engine reproduces EXACTLY are
// kept here — loose/alias spellings live in dictionary.hpp instead).
// Run: c++ -std=c++17 test.cpp -o phontest && ./phontest

#ifndef BANGLA_PHONETIC_CORPUS_HPP
#define BANGLA_PHONETIC_CORPUS_HPP
#include <cstddef>
namespace banglaphon {
struct CorpusCase { const char* input; const char* expected; const char* note; };
static const CorpusCase kCorpus[] = {
    {"o", "অ", "indep o"},
    {"a", "আ", "indep a"},
    {"i", "ই", "indep i"},
    {"u", "উ", "indep u"},
    {"e", "এ", "indep e"},
    {"O", "ও", "indep O"},
    {"onek", "অনেক", "word-initial vowel"},
    {"ka", "কা", "aa-kar"},
    {"ki", "কি", "i-kar"},
    {"ku", "কু", "u-kar"},
    {"ke", "কে", "e-kar"},
    {"kO", "কো", "o-kar"},
    {"kolom", "কলম", "inherent o"},
    {"bon", "বন", "inherent o"},
    {"boi", "বই", "inherent-o then indep-i"},
    {"bou", "বউ", "inherent-o then indep-u"},
    {"gan", "গান", "g"},
    {"chad", "ছাদ", "ch"},
    {"cad", "চাদ", "c"},
    {"kSh", "ক্ষ", "k+Sh"},
    {"kkh", "ক্ষ", "kkh shortcut"},
    {"jNGan", "জ্ঞান", "j+NG"},
    {"ostro", "অস্ত্র", "cluster"},
    {"kormo", "কর্ম", "reph (natural)"},
    {"korrmo", "কর্ম", "reph (rr)"},
    {"prem", "প্রেম", "ra-phola"},
    {"gram", "গ্রাম", "ra-phola"},
    {"fri", "ফ্রি", "ra-phola+i"},
    {"bidya", "বিদ্যা", "ya-phola"},
    {"bishwo", "বিশ্ব", "ba-phola"},
    {"ca^d", "চাঁদ", "chandrabindu"},
    {"bangla", "বাংলা", "anusvara"},
    {"rong", "রং", "anusvara end"},
    {"duHkho", "দুঃখ", "visarga"},
    {"2025", "২০২৫", "digits"},
    {"a.", "আ।", "danda"},
    {"amar", "আমার", "word"},
    {"tumi", "তুমি", "word"},
    {"kemon", "কেমন", "word"},
    {"omol", "অমল", "verified"},
    {"am", "আম", "verified"},
    {"ilish", "ইলিশ", "verified"},
    {"eed", "ঈদ", "verified"},
    {"uT", "উট", "verified"},
    {"rriShi", "ঋষি", "verified"},
    {"ek", "এক", "verified"},
    {"OShudh", "ওষুধ", "verified"},
    {"gha", "ঘা", "verified"},
    {"jhil", "ঝিল", "verified"},
    {"nodee", "নদী", "verified"},
    {"thuthu", "থুথু", "verified"},
    {"bhUt", "ভূত", "verified"},
    {"poribesh", "পরিবেশ", "verified"},
    {"sbasthyo", "স্বাস্থ্য", "verified"},
    {"raShTropoti", "রাষ্ট্রপতি", "verified"},
    {"songbidhan", "সংবিধান", "verified"},
    {"oviggota", "অভিজ্ঞতা", "verified"},
    {"drriShTivoNggi", "দৃষ্টিভঙ্গি", "verified"},
    {"odhyay", "অধ্যায়", "verified"},
    {"odhyapok", "অধ্যাপক", "verified"},
    {"korrtobyo", "কর্তব্য", "verified"},
    {"protyek", "প্রত্যেক", "verified"},
    {"biggan", "বিজ্ঞান", "verified"},
    {"ceShTa", "চেষ্টা", "verified"},
    {"bisheShoN", "বিশেষণ", "verified"},
    {"krriShi", "কৃষি", "verified"},
    {"unnoyon", "উন্নয়ন", "verified"},
    {"hoThat``", "হঠাৎ", "verified"},
    {"cheleTa Dim ar boRo mach khay.", "ছেলেটা ডিম আর বড় মাছ খায়।", "verified"},
    {"aShaRh", "আষাঢ়", "verified"},
    {"bishbobidyaloy", "বিশ্ববিদ্যালয়", "verified"},
    {"sbadheenota", "স্বাধীনতা", "verified"},
    {"korrtrripokkho", "কর্তৃপক্ষ", "verified"},
    {"dayitbo", "দায়িত্ব", "verified"},
    {"bastobayon", "বাস্তবায়ন", "verified"},
    {"protiShThan", "প্রতিষ্ঠান", "verified"},
    {"ontorrbhukto", "অন্তর্ভুক্ত", "verified"},
    {"bisheShoggo", "বিশেষজ্ঞ", "verified"},
    {"zuddho", "যুদ্ধ", "verified"},
    {"lomba", "লম্বা", "verified"},
    {"goNgga", "গঙ্গা", "verified"},
    {"brahmoN", "ব্রাহ্মণ", "verified"},
    {"chatro", "ছাত্র", "verified"},
    {"kromo", "ক্রম", "verified"},
    {"dhorrmo", "ধর্ম", "verified"},
    {"ryab", "র্যাব", "verified"},
    {"byakhya", "ব্যাখ্যা", "verified"},
    {"ba^sh", "বাঁশ", "verified"},
    {"ullas", "উল্লাস", "verified"},
    {"cihno", "চিহ্ন", "verified"},
    {"brohmo", "ব্রহ্ম", "verified"},
    {"uShNo", "উষ্ণ", "verified"},
    {"niShTha", "নিষ্ঠা", "verified"},
    {"skul", "স্কুল", "verified"},
    {"skholon", "স্খলন", "verified"},
    {"sthan", "স্থান", "verified"},
    {"spondon", "স্পন্দন", "verified"},
    {"sphoTik", "স্ফটিক", "verified"},
    {"poshcim", "পশ্চিম", "verified"},
    {"nishchidro", "নিশ্ছিদ্র", "verified"},
    {"utthan", "উত্থান", "verified"},
    {"dbeep", "দ্বীপ", "verified"},
    {"podmo", "পদ্ম", "verified"},
    {"shobdo", "শব্দ", "verified"},
    {"lobdho", "লব্ধ", "verified"},
    {"oNgko", "অঙ্ক", "verified"},
    {"akaNgkkha", "আকাঙ্ক্ষা", "verified"},
    {"bishleShoN", "বিশ্লেষণ", "verified"},
    {"udbastu", "উদ্বাস্তু", "verified"},
    {"antorrjatik", "আন্তর্জাতিক", "verified"},
    {"protidbondbita", "প্রতিদ্বন্দ্বিতা", "verified"},
    {"biruddho", "বিরুদ্ধ", "verified"},
    {"kromoborrdhoman", "ক্রমবর্ধমান", "verified"},
    {"atmohotya", "আত্মহত্যা", "verified"},
    {"onnoprashon", "অন্নপ্রাশন", "verified"},
    {"poriborrton", "পরিবর্তন", "verified"},
    {"sbeekrriti", "স্বীকৃতি", "verified"},
    {"sahityo", "সাহিত্য", "verified"},
    {"onuShThan", "অনুষ্ঠান", "verified"},
    {"grriho", "গৃহ", "verified"},
    {"Dheu", "ঢেউ", "verified"},
    {"gOlap", "গোলাপ", "verified"},
    {"mon", "মন", "verified"},
    {"kkhoma", "ক্ষমা", "verified"},
    {"poNGcom", "পঞ্চম", "verified"},
    {"gondho", "গন্ধ", "verified"},
    {"koShTo", "কষ্ট", "verified"},
    {"rasta", "রাস্তা", "verified"},
    {"uttor", "উত্তর", "verified"},
    {"rokto", "রক্ত", "verified"},
    {"durrneeti", "দুর্নীতি", "verified"},
    {"protinidhitbo", "প্রতিনিধিত্ব", "verified"},
    {"songskrriti", "সংস্কৃতি", "verified"},
    {"coNGcol", "চঞ্চল", "verified"},
    {"roNGjon", "রঞ্জন", "verified"},
    {"senT", "সেন্ট", "verified"},
    {"nTho", "ন্ঠ", "verified"},
    {"ThanDa", "ঠান্ডা", "verified"},
    {"khoND", "খণ্ড", "verified"},
    {"shanto", "শান্ত", "verified"},
    {"pontha", "পন্থা", "verified"},
    {"anondo", "আনন্দ", "verified"},
    {"bondhu", "বন্ধু", "verified"},
    {"kompon", "কম্পন", "verified"},
    {"sombhob", "সম্ভব", "verified"},
    {"somproday", "সম্প্রদায়", "verified"},
    {"ovinondon", "অভিনন্দন", "verified"},
    {"durrghoTona", "দুর্ঘটনা", "verified"},
    {"poristhiti", "পরিস্থিতি", "verified"},
    {"byoktitbo", "ব্যক্তিত্ব", "verified"},
    {"sangbadikota", "সাংবাদিকতা", "verified"},
    {"ovidhan", "অভিধান", "verified"},
    {"biporrzoy", "বিপর্যয়", "verified"},
    {"pratiShThanik", "প্রাতিষ্ঠানিক", "verified"},
    {"nirapotta", "নিরাপত্তা", "verified"},
    {"protyasha", "প্রত্যাশা", "verified"},
};
static const size_t kCorpusN = sizeof(kCorpus) / sizeof(kCorpus[0]);
} // namespace banglaphon
#endif // BANGLA_PHONETIC_CORPUS_HPP
